feat: add chart
Sefaria/LLM pull request #6
Opened 2024-02-12 09:28 UTC by BrendanGalloway

2024-02-12 10:44 UTC, dabasvibhor requested changes

2024-02-12 10:44 UTC, dabasvibhor commented on chart/templates/deployment.yaml
> +        image: "{{ .Values.deployment.image.registry }}/{{ .Values.deploment.image.name }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
typo: `deploment`

2024-02-12 10:44 UTC, dabasvibhor commented on chart/templates/deployment.yaml
> +  replicas: {{ .Values.deployment.replicaCount }}
missing in values.yaml

2024-02-13 11:15 UTC, nsantacruz approved these changes

2024-02-13 11:16 UTC, merged